version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000 && python manage.py migrate'
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'mysql-db'
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'

    volumes:
      - ./data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  celery:
    build: .
    command: celery -A School_Project worker -l INFO
    volumes:
      - ./:/app
    environment: # I have no idea why it should be like this
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - rabbitmq_uri = 'amqp://127.0.0.1:5672'
    depends_on:
      - rabbitmq
      - web
  celery-beat:
    build: .
    command: celery -A School_Project beat -l INFO
    volumes:
      - ./:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - rabbitmq_uri = 'amqp://127.0.0.1:5672'
    links:
      - rabbitmq

    depends_on:
      - rabbitmq
      - web

  cache:
   image: memcached:bullseye
   ports:
     - "11211:11211"
